// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZwqD4lhZXbud_ljd6HFXd6F1X3stMWW8',
    appId: '1:874226750713:web:d9f464bb67253d87207e28',
    messagingSenderId: '874226750713',
    projectId: 'flutter-exercise-monstarlab',
    authDomain: 'flutter-exercise-monstarlab.firebaseapp.com',
    storageBucket: 'flutter-exercise-monstarlab.appspot.com',
    measurementId: 'G-5YV0JQW07H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSgY222ssiOaHjdC4zsVCtSgwi5g43PVw',
    appId: '1:874226750713:android:b203e7e7df373958207e28',
    messagingSenderId: '874226750713',
    projectId: 'flutter-exercise-monstarlab',
    storageBucket: 'flutter-exercise-monstarlab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkt8eZ0K3NSS3WjiwSXYYjQg9FCyQzDXs',
    appId: '1:874226750713:ios:3994ff3aed18800f207e28',
    messagingSenderId: '874226750713',
    projectId: 'flutter-exercise-monstarlab',
    storageBucket: 'flutter-exercise-monstarlab.appspot.com',
    iosBundleId: 'com.example.equipementRequestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkt8eZ0K3NSS3WjiwSXYYjQg9FCyQzDXs',
    appId: '1:874226750713:ios:689becafb861150c207e28',
    messagingSenderId: '874226750713',
    projectId: 'flutter-exercise-monstarlab',
    storageBucket: 'flutter-exercise-monstarlab.appspot.com',
    iosBundleId: 'com.example.equipementRequestApp.RunnerTests',
  );
}
